version: "3.9"

networks:
  proxy:
    external: true
  lms_net:

services:
  backend:
    build: ./backend
    restart: always
    environment:
      - MONGO_URI=${MONGO_URI}
      - DB_NAME=${DB_NAME}
    depends_on:
      - mongo
    networks:
      - lms_net

  frontend:
    build: ./frontend
    restart: always
    environment:
      VIRTUAL_HOST: ${DOMAIN},www.${DOMAIN}
      LETSENCRYPT_HOST: ${DOMAIN},www.${DOMAIN}
      LETSENCRYPT_EMAIL: admin@${DOMAIN}
    depends_on:
      - backend
    networks:
      - proxy
      - lms_net

  mongo:
    image: mongo:6.0
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    networks:
      - lms_net

volumes:
  mongo-data:
