version: "3.9"

services:
  frontend:
    build: ./frontend
    container_name: lms-frontend
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: successscienceacademy.com,www.successscienceacademy.com
      LETSENCRYPT_HOST: successscienceacademy.com,www.successscienceacademy.com
      LETSENCRYPT_EMAIL: admin@successscienceacademy.com
    networks:
      - proxy
      - internal
    # expose optional
    expose:
      - "80"

  backend:
    build: ./backend
    container_name: lms-backend
    restart: unless-stopped
    environment:
      MONGO_URI: mongodb://mongo:27017
      DB_NAME: lms
    networks:
      - internal

  mongo:
    image: mongo:6.0
    container_name: lms-mongo
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    networks:
      - internal

volumes:
  mongo-data:

networks:
  proxy:
    external: true
  internal:
    driver: bridge
