name: Deploy LMS Website

on:
  push:
    branches: [ release ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Copy files to VPS
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        source: "."
        target: "/home/deploy/apps/lms"

    - name: Deploy on VPS
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          cd ~/apps/lms

          echo "DOMAIN=${{ secrets.DOMAIN }}" > .env
          echo "MONGO_URI=mongodb://mongo:27017" >> .env
          echo "DB_NAME=lms_db" >> .env

          docker compose -f docker-compose.prod.yml down
          docker compose -f docker-compose.prod.yml build
          docker compose -f docker-compose.prod.yml up -d
